---
version: "3.8"
services:
  web:
    build: .
    image: go3
    command: /venv/bin/python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file: ./go3/.env
    depends_on:
      migration:
        condition: service_completed_successfully
      db:
        condition: service_healthy
  worker:
    image: go3
    command: /venv/bin/python manage.py qcluster
    env_file: ./go3/.env
    depends_on:
      migration:
        condition: service_completed_successfully
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    restart: always
    env_file: ./go3/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "db_data:/var/lib/postgresql/data"
    ports:
      - "15432:5432"
  migration:
    image: go3
    command: /venv/bin/python manage.py migrate --noinput
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
